# Generated by Django 4.1.5 on 2023-02-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contacts_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='relationship',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contacts',
            name='cell_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contacts',
            name='land_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
