# Generated by Django 4.1.5 on 2023-03-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contacts_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
