# Generated by Django 4.1.5 on 2023-03-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
